name: Build docs 

on:
  pull_request:
  push:
    branches: [main]

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.12"]
        os: [ubuntu-latest]
      fail-fast: true

    steps:
    - id: install_pandoc
      run: sudo apt-get install pandoc
    - id: build docs
      uses: sphinx-notes/pages@v3
      with:
        documentation_path: ./docs/source
        requirements_path: ./requirements-dev.txt
